/**
 * @file    nvic.c
 * @brief   NVIC driver implementation for STM32F103
 *
 * @details
 * This file provides NVIC (Nested Vectored Interrupt Controller) functionality for STM32F103
 * microcontroller, including interrupt enable/disable, pending interrupt management, priority
 * configuration, and active interrupt status checking.
 *
 * @author  lu-05-cmd
 * @date    2026-04-27
 * @version 0.1.0
 *
 * @note
 * The implementation uses direct register access via NVIC peripheral base structures.
 * Supports configurable interrupt priorities and group-based priority management.
 **/



/*INCLUDE============================================================================================================================================================*/
#include <stdint.h>
#include "nvic.h"
#include "../scb/scb.h"



/**
 * @brief   Enable an interrupt request in NVIC
 * @param   IRQn: Interrupt request number (NVIC_IRQn_Position_t enum)
 * @note    This function sets the interrupt enable bit in the NVIC Interrupt Set-Enable Register (ISER)
 *          to enable the specified interrupt request. The interrupt must be enabled in NVIC before
 *          it can be generated and serviced.
 */
void NVIC_EnableIRQ(NVIC_IRQn_Position_t  IRQn)
{
    if(IRQn >= 0){
        NVIC->ISER[IRQn / 32] |= (1U << (IRQn % 32));
    }
}

/**
 * @brief   Disable an interrupt request in NVIC
 * @param   IRQn: Interrupt request number (NVIC_IRQn_Position_t enum)
 * @note    This function sets the interrupt disable bit in the NVIC Interrupt Clear-Enable Register (ICER)
 *          to disable the specified interrupt request. The interrupt will not be generated after
 *          being disabled, though pending interrupts may still be processed.
 */
void NVIC_DisableIRQ(NVIC_IRQn_Position_t IRQn)
{
    if(IRQn >= 0)
    {
        NVIC->ICER[IRQn / 32] |= (1U << (IRQn % 32));
    }
}

/**
 * @brief   Set pending status for an interrupt request
 * @param   IRQn: Interrupt request number (NVIC_IRQn_Position_t enum)
 * @note    This function sets the pending bit for the specified interrupt by writing to the NVIC
 *          Interrupt Set-Pending Register (ISPR). Setting a pending bit causes the interrupt
 *          to be treated as if it were generated by hardware, useful for software-triggered
 *          interrupts or testing interrupt handlers.
 */
void NVIC_SetPendingIRQ(NVIC_IRQn_Position_t IRQn)
{
    if(IRQn >=0)
    {
        NVIC->ISPR[IRQn / 32] |= (1U << (IRQn % 32));
    }
}

/**
 * @brief   Clear pending status for an interrupt request
 * @param   IRQn: Interrupt request number (NVIC_IRQn_Position_t enum)
 * @note    This function clears the pending bit for the specified interrupt by writing to the NVIC
 *          Interrupt Clear-Pending Register (ICPR). Clearing the pending bit prevents the
 *          interrupt from being serviced unless it is re-asserted by hardware.
 */
void NVIC_ClearPendingIRQ(NVIC_IRQn_Position_t IRQn)
{
    if(IRQn >= 0)
    {
        NVIC->ICPR[IRQn / 32] |= (1U << (IRQn % 32));
    }
} 

/**
 * @brief   Get pending status of an interrupt request
 * @param   IRQn: Interrupt request number (NVIC_IRQn_Position_t enum)
 * @retval  1 if the interrupt is pending, 0 if not pending
 * @note    This function reads the pending bit for the specified interrupt from the NVIC
 *          Interrupt Set-Pending Register (ISPR). Returns the pending status without modifying it.
 */
uint8_t NVIC_GetPendingIRQ(NVIC_IRQn_Position_t IRQn)
{
    return ((NVIC->ISPR[IRQn / 32] & (1U << (IRQn % 32))) ? 1U : 0U);
}

/**
 * @brief   Set priority level for an interrupt request
 * @param   IRQn: Interrupt request number (NVIC_IRQn_Position_t enum)
 * @param   prio: Priority level to set (0-255, lower values indicate higher priority)
 * @note    This function configures the interrupt priority by writing to the NVIC Interrupt
 *          Priority Registers (IPR). The priority value is shifted by (8 - __NVIC_PRIO_BIT) bits
 *          to align with the implemented priority bits in the STM32F103.
 */
void NVIC_SetPriority(NVIC_IRQn_Position_t IRQn, uint16_t prio)
{
    if(IRQn >= 0)
    {
        NVIC->IPR[IRQn] = (prio << (8 - __NVIC_PRIO_BIT));
    }
}

/**
 * @brief   Get priority level of an interrupt request
 * @param   IRQn: Interrupt request number (NVIC_IRQn_Position_t enum)
 * @retval  Priority level of the specified interrupt (0-255, -1 if IRQn is invalid)
 * @note    This function reads the interrupt priority from the NVIC Interrupt Priority Registers (IPR).
 *          Returns the raw priority value from the register.
 */
uint8_t NVIC_GetPriority(NVIC_IRQn_Position_t IRQn)
{
    if(IRQn >= 0)
    {
        return (uint8_t)NVIC->IPR[IRQn];
    }
    return -1;
}

/**
 * @brief   Get active status of an interrupt request
 * @param   IRQn: Interrupt request number (NVIC_IRQn_Position_t enum)
 * @retval  1 if the interrupt is currently active (being executed), 0 if not active
 * @note    This function reads the active bit for the specified interrupt from the NVIC
 *          Interrupt Active Bit Registers (IABR). Returns 1 only while the interrupt handler
 *          is executing, useful for detecting nested or recursive interrupt scenarios.
 */
uint32_t NVIC_GetActive(NVIC_IRQn_Position_t IRQn)
{
    if(IRQn >= 0)
    {
        return (NVIC->IABR[IRQn / 32] & (1U << (IRQn % 32))) ? 1U : 0U;
    }
    return 0U;
}

/* End of refactored NVIC */